FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["MigrationUtility/MigrationUtility.csproj","MigrationUtility/"]
RUN dotnet restore "MigrationUtility/MigrationUtility.csproj"
COPY . .

RUN dotnet build "MigrationUtility/MigrationUtility.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MigrationUtility/MigrationUtility.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MigrationUtility.dll"]
