version: '3.9'
services:
  web:
    build:
      dockerfile: Dockerfile-web
    ports:
      - 80:80
    depends_on:
      - api
    environment:
      - API_URL=http://api:80/api
    networks:
      - cg_network
  api:
    build:
      dockerfile: Dockerfile-api
    ports:
      - 8080:80
      - 8081:433
    networks:
      - cg_network
    environment:
      - ChallengeDB=Server=35.199.95.221;Database=challengeCG;User=sqlserver;Password=Admin1234!
  migrations:
    build:
      dockerfile: Dockerfile-migration
    networks:
      - cg_network
    environment:
      - ChallengeDB=Server=35.199.95.221;Database=challengeCG;User=sqlserver;Password=Admin1234!

networks:
  cg_network:
    driver: bridge